- hosts: localhost
  connection: local
  gather_facts: no
  vars:
    aws_region: "{{ lookup('env','AWS_REGION') }}"
  roles:
    - role: vpc
      tags: ["vpc"]
    - role: sns-topic
      tags: ["sns-topic"]
    - role: security-group
      tags: ["security-group"]
    - role: api
      tags: ["api"]
